import Head from 'next/head';

const Layout = ({ children, title = '' }) => {
    return (
        <>
            <Head>
                <title>Actious Dashboard | {title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='bg-gray-100 min-h-screen'>{children}</main>
        </>
    );
};

export default Layout;
